steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'scripts/pipeline-cloud/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pipeline-runner:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/pipeline-runner:latest'
timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_8'
